remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Shubhanshu Gupta]
description: [I'm a PhD student of Aerospace Engineering at Indian Institute of Technology, Kanpur. My field of specialization is Flight Dynamics and Controls.
I completed my bachelors in Electrical and Electronics Engineering from Visvesvaraya National Institute of Technology, Nagpur.
I have a strong interest in studying dynamics and control systems of hybrid VTOL vehicles.]
